apiVersion: v1
kind: Service
metadata:
  name: web-frontend
  namespace: posir
spec:
  type: "LoadBalancer"
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: web-frontend