apiVersion: v1
kind: Service
metadata:
  namespace: posir
  name: api
  labels:
    app: api
    type: LoadBalancer
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: api