apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: posir
  labels:
    app: worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: localhost:5000/factor
          envFrom:
            - configMapRef:
                name: factor-config
